os: linux
dist: bionic
language: node_js
node_js: 12
branches:
  only:
    - master
    - dev
    - /Release-v\d+\.\d+\.\d+/

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      os: windows
      addons:
        chrome: stable
      install:
        - npm install
      script:
        - npm run test:unit

    - stage: test
      os: osx
      addons:
        chrome: stable
      install:
        - npm install
      script:
        - npm run test:unit

    - stage: test
      os: linux
      env:
        secure: bZjWCQCogJjjcZSXp+aAuRuOnduCpHt2hNDtrxp9ZGrt5rVsulRBNzjjFOHcIPtrYqInToCpTnEScvm+KddRQ3QHzG8fkkoo+wSEzSa2Lgho/qZ5F4RQzY1jrz5ZxQrOGenr+SlaoF+IkV5ho79lR6H2uScI7niqOzwWCeoZiz9er8SaN/MEhdEXuiq8NynTkkkPtwYijM/38E9KBScZ2O7/ltlpqyQ0usc7d00Ydo/mlw+pb7ztTuiuYeJs5mAnZJ2RjuVd5Nbpm4QxOJeX8/hLYiQvMTlXN1JcOy1i/w5y9M9yq2yz0fKn367MoibACFmxQgkw218eC0v3pu5yAnBGvmbaIGJIwT9WofmRjNRTQ9hXemRbUetNQRhNriI9Ws8rfdieZnoJ35qDPnOijRx2zZPclo+3dLIiTj+AhYZjPsg9oEZ3DS8l/B1rCyXKYIudK3VQVI6YgAozKjsYSc/HP2tI0eB2Q+nyjHJlW1KBCGenCYM8KxnBKVOAs5T/9HI4ccJzSNjvPzQ49JqhsszMLsLYTnD3V6/NbX4tTw7Q3Lj6WNO05Mt2LQXzaByAs2bqmZ/FM4RkQrgyMnA36tb5f1NuthpRgwdckvb1lheo3+ibB5QldhLiBC4EdLuxqumiLF5RY0s/DsVOvkvYjo6KSouRxXkbXACYZIMdY/E=
      addons:
        chrome: stable
      install:
        - npm install
      before_script:
        - npm install --no-save coveralls
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - npm run test:unit -- --coverage
        - npm run test:e2e
      after_script:
        - cat ./coverage/lcov.info | coveralls
        - ./cc-test-reporter after-build --exit-code ${TRAVIS_TEST_RESULT}

    - stage: deploy
      os: linux
      script: skip
      before_deploy:
        - npm install
        - npm run build
        - export PACKAGE=$(npm pack --silent)
      deploy:
        provider: releases
        edge: true
        file: ${PACKAGE}
        release_notes_file: RELEASE.md
        token:
          secure: dgcb5HRqM4zQwFFPby1ybKRLovbN3Tj1z8gqGL1jm2EG182XM0QUIofV+DE6ujSVIv4E49K0klpc5WiNgN5G6FvmP4FYVdixYT94XlbRfCccgmIwDl++ldJSHny5CfpVeR3Uc4ikkhY0PYH+xJ4+y0nkASc/Z88EiNYS+mTZW5Cp0I3eY4ooMv8daJEpDoGv8ykpPspiLFaHGk1OZL0gHbwpICnElLePw6QxG7seSlYLcXC6J5/+tWv5x4jmpVH9PKG7L7COmPhATM2nMMS3J3Z/sybXDLeldERlPTR3kE639D5PT2xcRCuH5oUmQo88VEnmVawcVA3nieyWJDK9TxnTmHtgBaxw58BNybKCxcT8Z8M34EqrEIdtodTmsxqtj2Om52Arnyu1EHLh062cEI0dE6WSo+HV0xX3TsicFeCFKz/eoFGnK1rTNlSRRgHrnQNF2lTb44FVB3fV24YS3D4j0NmgHHbeo3ASRHc5JqFJdIGQlx0lJGTPCLFXm0MzQc273OOxgi5Jsa9Fca0UvqIHfeSKNTH7WBGjBkRHti6o5BnElvBIgNaKC3PnKiaIcwIWbFwnP19UIGMMoLn7doYUbkl6IBSaFJqTaaPum6PNECSzIxibnuSq0ZvKAH2jKO6B6cOzu2D9pM7COvd79RVH+0JcNTqDDEtzh+gJ7zs=
        on:
          repo: eidng8/xml-edit
          branch: /Release-v\d+\.\d+\.\d+/
          tags: true

    - stage: deploy
      os: linux
      script: skip
      before_deploy:
        - npm install
        - npm run build
      deploy:
        provider: npm
        edge: true
        email: cheung.jackey@gmail.com
        api_token:
          secure: NBPVxjDqy0tYwMCeeoZq/ntv+/aOdYpHWeuMXUjwE1BLbLlmwnfeSyBINoRQMs3wFWHInDVbcV7ZPMXR3cHDFl1gj2mH3DII5dQ/JeMKJW8mZE1FyZoUI9EIkoZQjPC6GrZ7CGCSvpHXXp/Il+vpQ5LHy4jkzGD0DWbPRM4BuK5qWIvlP6wQt9S+wjv4KpM4w0JeYLguYV6D5x5xlrg6DrG0UN7HfvHHif/0wxp1rdVxqKaFRGuEdGCHM5fWGanZO6bjvPYuh1Y9KxdigjGUvirzebxWzctjdwamzNwJDGmc82Frzr1rKCW/9+Bvw6CFJC/0vreYWRxfJzCdNDYpydm07sUunPLTf5gX48eQmO9NVGq7EnWiPTUwg6jc89f/b2MrysN8uZG8WSHcP6UGU8u6tHh98KTsi01Kn0SZGXZO3U0jsdx6+vp72OJbKDL5wMx8QkNUGWNXMROS2R7/D0r6mfAlAZx08Fbwdp/J3OTtCv8EsVEmLYbOQdNYGVC9SuTL8ITbQKxryRbTsEoq1kQ+6h/osNkUqqupA3ADjoxccz4uGl3+rB6xXCXubXb+oK3zir4bADgq81x2m7H3fg6s9Q7BDR3o0bc4w2bPQTDOEd+yfCvF/MXsZaxYhpEBEgVL8O3U87iMVY2Gj6m31dInMifIbmVYgIPjluU+F/E=
        on:
          repo: eidng8/xml-edit
          branch: /Release-v\d+\.\d+\.\d+/
          tags: true
